
connectivityPlugins:
  httpServer:
    libraryName: connectivity-http-server
    class: HTTPServer
  mapperCodec:
    libraryName: MapperCodec
    class: MapperCodec
  stringCodec:
    libraryName: connectivity-string-codec
    class: StringCodec
  diag:
    libraryName: DiagnosticCodec
    class: DiagnosticCodec

dynamicChainManagers:
  httpServerManager:
    transport: httpServer
    managerConfig:
      port: ${HTTPServer_port}
      staticFiles:
             /swagger.json:
                 file: ${PARENT_DIR}/swagger_HTTPServer.json
                 contentType: application/json
                 charset: UTF-8
             /index.html:
                 file: html/index.html
                 contentType: text/html
                 charset: UTF-8

dynamicChains:
  httpServer:
    - apama.eventMap:
        defaultEventType: MoodEvent
        defaultChannel: requests
    - mapperCodec:
        "*":
          towardsHost:
            mapFrom:
              - payload.requestId: metadata.requestId
            defaultValue:
              - payload.channel: "@{httpServer.responseChannel}"
          towardsTransport:
              mapFrom:
                - metadata.requestId: payload.requestId
              defaultValue:
                - metadata.http.statusCode: 200

    - diag: { tag: serverside }
    - jsonCodec
    - stringCodec
    - httpServer:
        automaticResponses: false
        responseTimeoutMs: 5000
        allowedMethods: [put]
